<?php

namespace Test\Pohoda;

use Pohoda\BankProbe;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-25 at 16:34:13.
 */
class BankProbeTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var BankProbe
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new BankProbe(\Ease\Shared::cfg('POHODA_BANK_IDS', ''));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Pohoda\BankProbe::setScope
     */
    public function testsetScope() {
        $this->object->setScope('yesterday');
        $this->assertInstanceOf(\DateTime::class, $this->object->getSince());
        $this->assertInstanceOf(\DateTime::class, $this->object->getUntil());

        $this->object->setScope('last_month');
        $this->assertInstanceOf(\DateTime::class, $this->object->getSince());
        $this->assertInstanceOf(\DateTime::class, $this->object->getUntil());
    }

    /**
     * @covers Pohoda\BankProbe::getUntil
     */
    public function testgetUntil() {
        $this->object->setScope('yesterday');
        $this->assertInstanceOf(\DateTime::class, $this->object->getUntil());
    }

    /**
     * @covers Pohoda\BankProbe::getSince
     */
    public function testgetSince() {
        $this->object->setScope('yesterday');
        $this->assertInstanceOf(\DateTime::class, $this->object->getSince());
    }

    /**
     * @covers Pohoda\BankProbe::accuntNumber
     */
    public function testaccuntNumber() {
        $this->assertIsString($this->object->accuntNumber());
    }

    /**
     * @covers Pohoda\BankProbe::getIban
     */
    public function testgetIban() {
        $this->assertIsString($this->object->getIban());
    }

    /**
     * @covers Pohoda\BankProbe::transactionsFromTo
     */
    public function testtransactionsFromTo() {
        $this->object->setScope('last_month');
        $this->assertIsArray($this->object->transactionsFromTo());
    }

    /**
     * @covers Pohoda\BankProbe::getColumnsFromPohoda
     */
    public function testgetColumnsFromPohoda() {
        $this->assertIsArray($this->object->getColumnsFromPohoda());
    }
}
