<?php

declare(strict_types=1);

/**
 * This file is part of the PohodaClientChecker package
 *
 * https://github.com/Spoje-NET/pohoda-client-checker
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\Pohoda;

use Pohoda\BankProbe;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-25 at 16:34:13.
 */
class BankProbeTest extends \PHPUnit\Framework\TestCase
{
    protected BankProbe $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new BankProbe(\Ease\Shared::cfg('POHODA_BANK_IDS', ''));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Pohoda\BankProbe::setScope
     */
    public function testsetScope(): void
    {
        $this->object->setScope('yesterday');
        $this->assertInstanceOf(\DateTime::class, $this->object->getSince());
        $this->assertInstanceOf(\DateTime::class, $this->object->getUntil());

        $this->object->setScope('last_month');
        $this->assertInstanceOf(\DateTime::class, $this->object->getSince());
        $this->assertInstanceOf(\DateTime::class, $this->object->getUntil());
    }

    /**
     * @covers \Pohoda\BankProbe::getUntil
     */
    public function testgetUntil(): void
    {
        $this->object->setScope('yesterday');
        $this->assertInstanceOf(\DateTime::class, $this->object->getUntil());
    }

    /**
     * @covers \Pohoda\BankProbe::getSince
     */
    public function testgetSince(): void
    {
        $this->object->setScope('yesterday');
        $this->assertInstanceOf(\DateTime::class, $this->object->getSince());
    }

    /**
     * @covers \Pohoda\BankProbe::accuntNumber
     */
    public function testaccuntNumber(): void
    {
        $this->assertIsString($this->object->accuntNumber());
    }

    /**
     * @covers \Pohoda\BankProbe::getIban
     */
    public function testgetIban(): void
    {
        $this->assertIsString($this->object->getIban());
    }

    /**
     * @covers \Pohoda\BankProbe::transactionsFromTo
     */
    public function testtransactionsFromTo(): void
    {
        $this->object->setScope('last_month');
        $this->assertIsArray($this->object->transactionsFromTo());
    }

    /**
     * @covers \Pohoda\BankProbe::getColumnsFromPohoda
     */
    public function testgetColumnsFromPohoda(): void
    {
        $this->assertIsArray($this->object->getColumnsFromPohoda());
    }
}
